[package]
name = "crisp_test"
version = "0.1.0"
edition = "2021"
authors = ["jupitersky", "kipcode66"]
publish = false
categories = ["development-tools", "parser-implementations"]

[dependencies]
crisp = { path = "../../crisp" }