[package]
name = "crisp-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0"
syn = { version = "^2.0", features = ["extra-traits"] } # Use "extra-traits" feature when debugging macros. (increases compile time a lot)
quote = "^1.0"